# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Authenticate for GCP'
description: 'Authenticate a workflow for Protobuf CI testing'
inputs:
  credentials:
    required: true
    description: "The GCP credentials to use for GCP"
    type: string

outputs:
  credentials-file:
    description: "Credentials file generated for GCP"
    value: ${{ steps.output.outputs.credentials-file }}

runs:
  using: 'composite'
  steps:
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d # v1.0.0
      if: ${{ env.CREDENTIALS_FILE == '' }}
      with:
        credentials_json: ${{ inputs.credentials }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@e30db14379863a8c79331b04a9969f4c1e225e0b # v1.1.1
      if: ${{ env.CREDENTIALS_FILE == '' }}
      with:
        version: ">= 446.0.0"
    - name: Use gcloud CLI
      shell: bash
      run: gcloud info

    - name: Store credentials path
      if: ${{ env.CREDENTIALS_FILE == '' }}
      shell: bash
      run: echo "CREDENTIALS_FILE=${{ steps.auth.outputs.credentials_file_path }}" >> $GITHUB_ENV

    - name: Output credentials file
      id: output
      shell: bash
      run: echo "credentials-file=${{ env.CREDENTIALS_FILE }}" >> $GITHUB_OUTPUT
