# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Composer Setup'
description: 'Run a Bazel-based docker image for Protobuf CI testing'
inputs:
  cache-prefix:
    required: true
    description: A unique prefix to prevent cache pollution
    type: string
  directory:
    required: false
    description: The directory containing composer.json

runs:
  using: 'composite'
  steps:
    - name: Cache Composer dependencies
      #if: ${{ github.event_name != 'pull_request' && github.event_name != 'pull_request_target' }}
      if: ${{ github.event_name != 'pull_request_target' }}
      uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: composer-${{ inputs.cache-prefix }}-${{ hashFiles(format('{0}/composer.json', inputs.directory)) }}

    - name: Restore Bazelisk
      #if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
      if: ${{ github.event_name == 'pull_request_target' }}
      uses: actions/cache/restore@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.2.4
      with:
        path: /tmp/composer-cache
        key: composer-${{ inputs.cache-prefix }}-${{ hashFiles(format('{0}/composer.json', inputs.directory)) }}

    - uses: php-actions/composer@v6
      with:
        args: --ignore-platform-reqs --working-dir=${{ inputs.directory }}

    - name: Fix permissions
      shell: bash
      run: chmod 777 ${{ inputs.directory }}/composer.lock
