# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Setup CI Runner
# TODO(b/267357823) Consider moving this to it's own repository so we can
# include the call to actions/checkout.
description: Setup any platform-specific adjustments we need to make for CI
runs:
  using: 'composite'
  steps:
    - name: Fix Windows line breaks
      if: runner.os == 'Windows'
      shell: bash
      run: find . -type f -print0 | xargs -0 d2u 2>/dev/null

    - name: Install bazelrc files
      shell: bash
      run: >
        cp -f ci/*.bazelrc .
        && cp -f ${{ runner.os }}.bazelrc .bazelrc
        || echo "No ci folder found"
