# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'CCache Setup'
description: 'Run a Bazel-based docker image for Protobuf CI testing'
inputs:
  cache-prefix:
    required: true
    description: A unique prefix to prevent cache pollution
    type: string
  support-modules:
    required: false
    description: Whether or not we need to support modules.  This can result in extra cache misses.
  vsversion:
    required: false
    default: '2019'
    description: The version of Visual Studio to use (Windows only)
    type: string
  ccache-version:
    required: false
    default: '4.8'
    description: A pinned version of ccache
    type: string
  windows-arch:
    required: false
    default: 'x64'
    description: The architecture to use (Windows only)
    type: string

runs:
  using: 'composite'
  steps:
    - name: Symlink current Actions repo
      env:
        GH_ACTION_DIR: ${{ github.workspace }}/../../_actions/${{ github.action_repository }}/${{ github.action_ref }}/
        GH_ACTION_CLONE: ${{ github.workspace }}/../../_actions/current
      shell: bash
      run: ln -fs $GH_ACTION_DIR $GH_ACTION_CLONE

    - name: Configure ccache environment variables
      shell: bash
      run: |
        echo "CCACHE_BASEDIR=${{ github.workspace }}" >> $GITHUB_ENV
        echo "CCACHE_DIR=${{ github.workspace }}/.ccache" >> $GITHUB_ENV
        echo "CCACHE_COMPRESS=true" >> $GITHUB_ENV
        echo "CCACHE_COMPRESSLEVEL=5" >> $GITHUB_ENV
        echo "CCACHE_MAXSIZE=150M" >> $GITHUB_ENV
        echo "CCACHE_SLOPPINESS=clang_index_store,include_file_ctime,include_file_mtime,file_macro,time_macros" >> $GITHUB_ENV
        echo "CCACHE_DIRECT=true" >> $GITHUB_ENV

    - name: Setup ccache on Windows
      if: ${{ runner.os == 'Windows' }}
      uses: ./../../_actions/current/internal/ccache-setup-windows
      with:
        ccache-version: ${{ inputs.ccache-version }}
        vsversion: ${{ inputs.vsversion }}
        arch: ${{ inputs.windows-arch }}
    - name: Setup ccache on Mac
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: brew install ccache

    - name: Configure ccache cmake arguments
      shell: bash
      run: |
        echo "CCACHE_CMAKE_FLAGS=-Dprotobuf_ALLOW_CCACHE=ON -DCMAKE_C_COMPILER_LAUNCHER=$(which ccache || echo 'ccache') -DCMAKE_CXX_COMPILER_LAUNCHER=$(which ccache || echo 'ccache')" >> $GITHUB_ENV
        which ccache || echo "No local ccache installation found"
        ccache --version || echo "No local ccache installation found"

    - name: Setup fixed path ccache caching
      uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.2.4
      with:
        path: |
          .ccache/**
          !.ccache/lock
          !.ccache/tmp
        # Always push to a cache key unique to this commit.
        key: ${{ format('ccache-{0}-{1}-{2}', inputs.cache-prefix, github.ref_name, github.sha) }}
        # Select a cache to restore from with the follow order of preference:
        # 1) The exact same commit we're running over
        # 2) The latest cache from the current ref branch
        # 3) The latest push to the base ref of a pull request
        restore-keys: |
          ${{ format('ccache-{0}-{1}-{2}', inputs.cache-prefix, github.ref_name, github.sha) }}
          ${{ format('ccache-{0}-{1}', inputs.cache-prefix, github.ref_name) }}
          ${{ format('ccache-{0}-{1}', inputs.cache-prefix, github.base_ref) }}

    - name: Enable module support
      if: ${{ inputs.support-modules }}
      shell: bash
      run: |
        echo "CCACHE_SLOPPINESS=$CCACHE_SLOPPINESS,modules" >> $GITHUB_ENV
        echo "CCACHE_DEPEND=true" >> $GITHUB_ENV

    - name: Zero out ccache
      if: ${{ runner.os != 'Linux' }}
      shell: bash
      run: ccache -z
