# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Non-Bazel Bash Run'
description: 'Run a bash script for Protobuf CI testing with a non-Bazel build system'
inputs:
  credentials:
    required: true
    description: "The GCP credentials to use for reading the docker image"
    type: string
  command:
    required: true
    description: A command to run in the docker image
  bazel-version:
    required: false
    description: Bazel version to use
    default: "6.4.0"
    type: string

runs:
  using: 'composite'
  steps:
    - name: Symlink current Actions repo
      env:
        GH_ACTION_DIR: ${{ github.workspace }}/../../_actions/${{ github.action_repository }}/${{ github.action_ref }}/
        GH_ACTION_CLONE: ${{ github.workspace }}/../../_actions/current
      shell: bash
      run: ln -fs $GH_ACTION_DIR $GH_ACTION_CLONE

    - name: Setup Runner
      uses: ./../../_actions/current/internal/setup-runner

    - name: Update stale files using Bazel
      uses: ./../../_actions/current/bazel
      with:
        credentials: ${{ inputs.credentials }}
        bazel-cache: regenerate-stale-files
        bash: ./regenerate_stale_files.sh $BAZEL_FLAGS
        version: ${{ inputs.bazel-version }}

    - name: Run
      shell: bash
      run: |
        set -ex
        ${{ inputs.command }}
